FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY scripts/ ./scripts/
COPY tests/mocks/ ./tests/mocks/

CMD ["python", "-m", "app.queue.consumer"]
